name: Release PDF Artifacts

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  render:
    uses: ./.github/workflows/render.yml

  release:
    if: github.event.pull_request.merged == true
    needs: render
    runs-on: ubuntu-latest

    steps:
      - name: Download PDF artifacts
        uses: actions/download-artifact@v4
        with:
          name: booklet-pdfs # Ensure this matches the name used in the upload step

      - name: List downloaded PDF files
        run: ls -la ./renderer

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_id }} # Create a unique tag name
          name: Release ${{ github.run_id }} # Name of the release
          body: |
            This release was generated automatically upon a successful merge (new article added).
          files: ./renderer/*.pdf # Path to the downloaded PDF files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
