name: Release PDF Artifacts

on:
  workflow_run:
    workflows: ["Generate Booklet PDF files"] # Name of the workflow to listen for
    branches: [master] # Only run on the master branch
    types:
      - completed # Trigger on completion

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only proceed if the previous workflow succeeded
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download PDF artifacts
        uses: actions/download-artifact@v3
        with:
          name: booklet-pdfs # Ensure this matches the name used in the upload step

      - name: List downloaded PDF files
        run: ls -la ./renderer

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_id }} # Create a unique tag name
          name: Release ${{ github.run_id }} # Name of the release
          body: |
            This release was generated automatically upon a successful merge (new article added).
          files: ./renderer/*.pdf # Path to the downloaded PDF files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
