name: Generate PDF from Markdown and SVG

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache apt package lists and downloaded deb files
        uses: actions/cache@v3
        with:
          # Cache apt package lists and downloaded package files
          path: |
            /var/cache/apt/archives/**.deb
            !/var/cache/apt/archives/partial
            !/var/cache/apt/archives/lock
          key: apt-packages-cache
          restore-keys: |
            ${{ runner.os }}-apt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc inkscape texlive-latex-base texlive-fonts-extra poppler-utils

      - name: Run the PDF rendering script in the renderer folder
        run: make
        working-directory: renderer

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: booklet-pdf
          path: renderer/2024_TILICS.pdf
